### ISSUE TITLE
Any issue not calling `client.destroy() ` before app shut down?

### ISSUE THREAD

**Issue by jiusongtripactions** [splitio/android-client#409]
Hi Split,
I see Android sdk guide recommend us to call `client.destroy() ` before shut down app, is there a specific reason we need to do this? Is there any potential issue if we don't call it?

There are actually some cases we are having user issues if we call this `client.destroy() ` because it also clears cache.
Like for a logged in user, if we call this and clears cache, the next time user launches the app, and split for some reason failed, we don't have any cached config for this user, then we need to fall back to a very old state for this user, but not the latest cached state.

If we do need to call this `client.destroy()`, would it make sense to break it into two APIs?
Something like `client.close()` and `client.clearCache()`?  so we could decide if we want to keep the cache or not?

Looking forward to hear back from you,

Thanks & Regards,
Jiusong

**Comment by chillaq** [comment]
Hi @jiusongtripactions, thanks for the info. We recommend calling client.destroy() to flush the impressions and events that are cached locally. The actual split information will remain in the cache which is in the app filesystem, so that will not be cleared or removed. 
When the app starts again, the SDK detects the existing cache and will only need to sync the changes from split cloud, which is a much faster call.

If you see the whole cache getting deleted when calling client.destroy, please let us know, this should not happen.

Thanks
Bilal

**Comment by jiusongtripactions** [comment]
Hi, @chillaq 
Thanks for your quick response and detailed explanation.
I tested it by calling `clident.destory()`, looks like cache is still there.

Thanks!
Jiusong
